# Generated by Django 4.1.2 on 2022-10-31 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uit_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uit_app.student')),
            ],
        ),
    ]
