# Generated by Django 4.1.2 on 2022-11-04 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uit_app', '0004_department_student_image_delete_information_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='department',
            new_name='department_name',
        ),
    ]
