# Generated by Django 4.1.2 on 2022-11-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uit_app', '0005_rename_department_department_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='s_session',
            field=models.CharField(default='2022-2026', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(upload_to='StudentImage'),
        ),
    ]
