# Generated by Django 3.2.15 on 2022-11-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uit_app', '0007_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='TeacherProfile')),
            ],
        ),
    ]
